### ISSUE TITLE
Request: Config option to disable "Combat Spirit" Synergy

### ISSUE THREAD

**Issue by NightKosh** [MidnightsFX/Jewelcrafting_Epic_Jewels#2]
Hello. I'd like to ask you to add configuration option to disable "Combat Spirit" synergy

**Comment by MidnightsFX** [comment]
Hey you can use Jewelcrafting advanced yaml configuration to disable this, or change the requirements or power etc.

In order to enable that you need to set `Use External YAML = On` in the Jewecrafting config file. You would then need to place a copy of the file [Jewelcrafting.Synergy.yml](https://github.com/blaxxun-boop/Jewelcrafting/blob/master/Jewelcrafting/Effects/Jewelcrafting.Sockets.yml) in your config directory (this file _only_ includes the JC synergies, if you want any of the modded ones you would need to add them below).

[Here](https://github.com/MidnightsFX/Jewelcrafting_Epic_Jewels/blob/master/EpicJewels/AssetsEmbedded/EJConfig.yaml#L272) is the definition for EJs synergies.

You can use the specified file to remove, modify or change the powers, or power amounts provided by the synergies.

For example, this replaces the synergy normally used for  spirit wolf with a synergy bonus to weaponmaster.

```yaml
Have opal = amethyst > 3 of each:
  conditions:
    - opal > 3
    - amethyst > 3
    - opal = amethyst
  effect:
    Weapon Master: 5
```

Below is the whole file example- if you need. It should be named `Jewelcrafting.Synergy.yml` and would be placed in `BepinEx/Config`
(the following file uses the above example that replaces combat spirit with weaponmaster:5)
```yaml
at least six red and no blue:
  conditions:
    - red > 5
    - blue = 0
  effect:
    pyromaniac: 20

exactly three yellow:
  conditions:
    - yellow = 3
  effect:
    resonating echoes: 20
    
same number of all colors:
  conditions:
    - min all = max all
    - min all > 0
  effect:
    equilibrium: 3
    
more red than black and purple combined:
  conditions:
    - red > purple + black
    - purple >= 2
    - black >= 2
  effect:
    eternal student: 20

same number of green and blue:
  conditions:
    - green = blue
    - green >= 2
  effect:
    time warp: 10
    
many gems:
  conditions:
    - sum all >= 12
  effect:
    careful cutting: 2
    
twice as much yellow than black:
  conditions:
    - yellow = black * 2
    - yellow > 0
  effect:
    turtle embrace: 20
    
purple as the most common:
  conditions:
    - purple > max other
    - purple > 0
  effect:
    bloodthirsty: 10

Have opal = amethyst > 3 of each:
  conditions:
    - opal > 3
    - amethyst > 3
    - opal = amethyst
  effect:
    Weapon Master: 5

Have at least 7 garnets:
  conditions:
    - garnet > 6
  effect:
    Intense Fire: 25

Have 6 amber and 6 jade:
  conditions:
    - amber = 6
    - jade = 6
  effect:
    Weapon Master: 15

Have at least 6 aquamarine:
  conditions:
    - aquamarine > 5
  effect:
    Slippery When Wet: 35

Have at least 13 aquamarine:
  conditions:
    - aquamarine > 12
  effect:
    Waterproof: 1

Have at least 9 amethyst, 6 opal, and 3 amber:
  conditions:
    - amethyst > 8
    - opal > 5
    - amber > 2
  effect:
    Spellsword: 45
```
